### ISSUE TITLE
Layout chech cross talk

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#100]
Apologies if this is stating the obvious but: during the layout review please check that all sensitive analog lines (clocks, dac outputs etc) are well separated from noise sources like smps or digital lines. I’m particularly concerned about the afe dio lines (lvds adc) so let’s do everything we can to screen them from the dac, lo, etc

**Comment by hartytp** [comment]
@marmeladapk did you check this when you did your design review? If so, can you close this please?

Same for the other open issues.

**Comment by marmeladapk** [comment]
@filipswit

**Comment by hartytp** [comment]
@gkasprow @marmeladapk what about all the other open issues? Are these boards ready for manufacture? If so, can the other issues be closed?

**Comment by marmeladapk** [comment]
@gkasprow needs to close them once they are done.

**Comment by hartytp** [comment]
OKay. But, just to check we're on the same page, the boards aren't ready to send off for manufacture until these are all closed, right? What's the timeline for that? When can we get Sayma to the board house???

**Comment by gkasprow** [comment]
I went through this issue and optimised a little the layout increasing separation between ADC LVDS lines. 
DAC and LO lines are far away.
