### ISSUE TITLE
DAC SYSREF signal format

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_RTM#116]
What signal format should be programmed into the HMC7043 for DAC SYSREF?
This says "CML HP" (is that a reference to the "high power" mode of the HMC7043?):
![image](https://user-images.githubusercontent.com/720864/67107867-dc826b80-f1ff-11e9-8325-91c88669bef2.png)
This says "LVDS" (are the 50 ohm resistors above supposed to convert CML HP to LVDS? Why not use LVDS output directly from the HMC7043 then?):
![image](https://user-images.githubusercontent.com/720864/67107936-f7ed7680-f1ff-11e9-8b79-59c99e815788.png)

**Comment by sbourdeauducq** [comment]
And how should this one be configured:
![image](https://user-images.githubusercontent.com/720864/67108284-c1fcc200-f200-11e9-8a1b-9a66f97c3e70.png)

**Comment by gkasprow** [comment]
the outputs with resistors to GND are LVPECL, the ones without are CML. We need internal resistors in the case of CML. 100R should work. I'm not 100% sure but LVDS probably were not strong enough to drive the DAC.
