### ISSUE TITLE
photos

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Sayma_RTM#121]
Please post photos of the stuffed Sayma_RTM for contract accounting.

> Sayma RTM v2.0: print 10 PCBs, stuff 6

**Comment by akaminska** [comment]
1907180PW0008A0103
![IMG_20191213_170232](https://user-images.githubusercontent.com/45766037/78686116-f53c2600-78f2-11ea-90dd-429de9483594.jpg)
![IMG_20191213_170245](https://user-images.githubusercontent.com/45766037/78686131-fa00da00-78f2-11ea-8778-065126f89498.jpg)

**Comment by akaminska** [comment]
1907180PW0008A0104
![IMG_20191213_170915](https://user-images.githubusercontent.com/45766037/78686448-5106af00-78f3-11ea-96ff-f2ca54171dcd.jpg)
![IMG_20191213_170929](https://user-images.githubusercontent.com/45766037/78686463-57952680-78f3-11ea-8875-7bedaf83504e.jpg)

**Comment by akaminska** [comment]
1907180PW0008A0107
![IMG_20191213_171254](https://user-images.githubusercontent.com/45766037/78686527-72679b00-78f3-11ea-81b0-fb727c9b180a.jpg)
![IMG_20191213_171302](https://user-images.githubusercontent.com/45766037/78686532-74c9f500-78f3-11ea-83f9-c6607ec7b43d.jpg)

**Comment by akaminska** [comment]
1907180PW0008A0105
![IMG_20191213_173936](https://user-images.githubusercontent.com/45766037/78686593-89a68880-78f3-11ea-9efa-5eaef3021651.jpg)
![IMG_20191213_173945](https://user-images.githubusercontent.com/45766037/78686635-94f9b400-78f3-11ea-979b-7c11044735a5.jpg)

**Comment by akaminska** [comment]
1907180PW0008A0106
![IMG_20191216_171045](https://user-images.githubusercontent.com/45766037/78686673-9fb44900-78f3-11ea-97c0-f16491e7dba5.jpg)
![IMG_20191216_171056](https://user-images.githubusercontent.com/45766037/78686683-a2af3980-78f3-11ea-87db-62838ce061c7.jpg)

**Comment by akaminska** [comment]
1907180PW0008A0108
![IMG_20191216_171320](https://user-images.githubusercontent.com/45766037/78686804-c6727f80-78f3-11ea-84c1-b679f8917868.jpg)
![IMG_20191216_171329](https://user-images.githubusercontent.com/45766037/78686835-cd00f700-78f3-11ea-9cd7-b8b1dabf2951.jpg)

**Comment by akaminska** [comment]
Unpopulated PCBs
![IMG_2539](https://user-images.githubusercontent.com/45766037/78687157-2cf79d80-78f4-11ea-8c0f-a6117e01b0a6.jpg)
![IMG_2541](https://user-images.githubusercontent.com/45766037/78687215-3bde5000-78f4-11ea-8064-e89251a5024e.jpg)

**Comment by jbqubit** [comment]
Thank you. Please also post photo of one board with rear panel installed.

**Comment by akaminska** [comment]
Please remember that these panels are "prototypes" as well, we definitely aim for better quality for the final product...
![SAYMA RTM 1907180PW0008A0107 PANEL](https://user-images.githubusercontent.com/45766037/79003212-6d545700-7b52-11ea-9c14-c23cc79ba7fd.JPG)
![SAYMA RTM 1907180PW0008A0107 GÓRA](https://user-images.githubusercontent.com/45766037/79003230-79d8af80-7b52-11ea-90f8-d8b50f125233.JPG)

**Comment by jbqubit** [comment]
Looks good. Thank you!

**Comment by hartytp** [comment]
Did anyone take a nice photo of Sayma AMC + RTM with panels and BaseMod fitted?
