### ISSUE TITLE
Sysref driving

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#13]
@gkasprow how do you want to drive the AD9154 SYSREF? IIRC it should ideally be driven DC coupled with a common-mode voltage of 600mV (but someone should check this during the design review). That's not directly compatible with LVPECL without a RC termination network.

**Comment by hartytp** [comment]
- [ ] even though this will be DC coupled, please ensure that there are suitable pads that can be used to add AC coupling capacitors later on if we find it necessary

**Comment by hartytp** [comment]
cf https://github.com/sinara-hw/Sayma_RTM/issues/17

**Comment by hartytp** [comment]
NB fwiw, the eval board has the SYSREF AC coupled, with a test point used to drive/probe the DC level.

IIRC the data sheet implies that SYSREF should be DC coupled where possible.

I would like to ensure that we can drive SYSREF either DC or AC coupled (choice by population options), with DC coupling being the default choice.

**Comment by gkasprow** [comment]
If SYSREF is going to be a non-50% duty cycle, we must use DC coupling. We must make sure DAC accepts LVPECL common model

**Comment by hartytp** [comment]
> We must make sure DAC accepts LVPECL common model

I don't think it does. IIRC the pin self-biases to 600mV (there is a figure in the data sheet that shows the simplified schematic for the input configuration), which is the common-mode voltage it's designed to work at. I don't think the common-mode voltage of LVPECL/CML will do the job.

**Comment by marmeladapk** [comment]
Now SYSREF is AC coupled (and capacitors don't have values on schematics).

**Comment by gkasprow** [comment]
@hartytp the SYSREF and CLOCK will accept LVPECL signals directly.
![obraz](https://user-images.githubusercontent.com/4325054/53499070-ef490400-3aa7-11e9-8b23-5a4ffb69c8aa.png)

So we can DC-couple them with HMC7043

**Comment by gkasprow** [comment]
well, not really. The high level of LVPECL can be even 2.4V. So out of the common mode of the DAC.
Do AC-coupling cause any issue? Certainly, we are not over-driving the inputs. I added the series 50Ohm resistors to lower the clock amplitude.

**Comment by hartytp** [comment]
@gkasprow the thing I'm conscious of is that the default (self-biasing/AC coupling) DAC input common-mode bias voltage is only 600mV. I believe that it can work with other common-mode voltages, as indicated by the data sheet, but requires a larger swing to operate correctly. There is an equivalent circuit of the input stage that shows how this works.

So, I'm wary of DC coupling LVPECL in to the DAC unless we really think about it.

**Comment by gkasprow** [comment]
So let's leave it as it is now.

**Comment by hartytp** [comment]
@gkasprow can you confirm:
1. SYSREF is DC coupled into the DAC (although, let's make sure there are pads for AC coupling). IIRC currently SYSREF is AC coupled
2. DAC clocks and SYSREF are correctly terminated
3. which HMC7043 output standards is this designed to use (let's make sure that's annotated on the schematic)
4. that the common-mode voltage and voltage swing are appropriate for both the DAC clock and SYSREF

Once that's done we can close this issue

**Comment by gkasprow** [comment]
to make SYSREF DC-coupled I have to lower the LVPECL output to less than 2V.
LVDS mode does not meet minimum 400mVpp DAC requirement.
So either we use CML mode that has VCC-1.6V common mode voltage or LVPECL with resistive divider.
I suggest using direct CML mode with series resistors that will reduce the swing
![obraz](https://user-images.githubusercontent.com/4325054/53506777-f7f50680-3ab6-11e9-8fc0-c46ef20817e1.png)
two 50R resistors should do the job and preserve common mode

**Comment by gkasprow** [comment]
Let's keep the 200R DNP so we can always use them and replace 49R9 with 100nF and revert to AC coupling.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/53507694-a188c780-3ab8-11e9-99c4-d6c42103e77f.png)

**Comment by hartytp** [comment]
Do you need to add termination to Vcc at the DAC then?

**Comment by hartytp** [comment]
(if you're using CML for SYSREF that is)

**Comment by hartytp** [comment]
Also, are you sure that 3.3-1.6=1.7V common-mode will work for the DAC SYSREF?

**Comment by gkasprow** [comment]
It accepts it up to 2V so with reduced swing should work.

**Comment by gkasprow** [comment]
HMC has internal termination for CML mode
![obraz](https://user-images.githubusercontent.com/4325054/53511374-98035d80-3ac0-11e9-9980-63013a8ba5d7.png)

**Comment by hartytp** [comment]
Okay. Can you leave resistor pads so that we can make a divider between Vcc and GND if we need to modify the voltage swing/DC bias point.

**Comment by gkasprow** [comment]
OK, I will add 2 DNP resistors to GND to make such divider.
