### ISSUE TITLE
Pull UPs-downs

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#14]
- [ ] HMC830 SPI needs pull ups/downs to ensure it starts in a sensible state. Should we add this for the ADF PLL as well?

**Comment by hartytp** [comment]
Might also be worth ensuring that the SYSREF delay line outputs are disabled (pulled low) until EN is actively driven high by the RTM FPGA

**Comment by gkasprow** [comment]
not relevant anymore
