### ISSUE TITLE
CDR clean 2

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#15]
@sbourdeauducq do we need this, or can we just use use the MGT REF CLK? If we remove this signal, we can scrap a clock buffer to save some money/power/complexity in the clock tree

**Comment by jbqubit** [comment]
@hartytp This isn't the time to try to optimize Sayma v2 money/power/complexity. The current plan is to keep the number of v1 vs v2 diffs to a minimum.

**Comment by hartytp** [comment]
> The current plan is to keep the number of v1 vs v2 diffs to a minimum.

The purpose of this is not to minimise the number of design changes, it's to maximise the probability of arriving at a working design given the available resources.

While I appreciate the enthusiasm, I'm not convinced the current spray of comments is entirely productive. Chill out and let's focus on having a solid technical strategy here rather than knee-jerk reactions.

**Comment by hartytp** [comment]
Aside from the obvious point that unnecessary components can still introduce bugs and break an otherwise working design, they have to be checked carefully as part of the design review and then tested before the hardware is shipped, and then configured from firmware. This all leads to delays. If this components is genuinely not going to be needed then it is likely to be quicker to remove it than to keep it.

**Comment by jbqubit** [comment]
> I'm not convinced the current spray of comments is entirely productive. 

Please respond to my comments in the respective Issues.

**Comment by jbqubit** [comment]
OK. Let's see what @sbourdeauducq says.

**Comment by gkasprow** [comment]
Let's keep it as it is.
