### ISSUE TITLE
FPGA_CFG_DIN

### ISSUE THREAD

**Issue by tprzywoz** [sinara-hw/Sayma_RTM#24]
Should be connected to DIN (pin L17) not MOSI (K16)

**Comment by gkasprow** [comment]
Are U sure?
It was connected like this in first revision and did not work.
We do not use master serial with FLASH but slave serial.
Bitstream is loaded by AMC FPGA.
So  the data goes to D00.

**Comment by tprzywoz** [comment]
Yes, I know that is slave serial.
From 7 Series FPGAs Configuration (UG470):
![image](https://user-images.githubusercontent.com/30114557/50821030-6bd42780-132e-11e9-8c81-be2eab716885.png)
"The Master Serial configuration mode is the same as the Slave Serial configuration mode,
except that the FPGA generates the CCLK."

In v0.97 schematics there is also connection to MOSI, so looks like nothing was changed.

**Comment by gkasprow** [comment]
hm, I'm pretty sure that changed this. But I had a lot of issues with Xpedition so maybe the change was not saved correctly..
Thanks.
