### ISSUE TITLE
FPGA pinout

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Sayma_RTM#25]
@gkasprow for the stub ARTIQ port we need the FPGA pinout

**Comment by gkasprow** [comment]
Here you go.
[Sayma_RTM_pins.txt](https://github.com/sinara-hw/Sayma_RTM/files/2753098/Sayma_RTM_pins.txt)

**Comment by gkasprow** [comment]
here is an updated version. Some missing labels added.
[FPGA_pins.xlsx](https://github.com/sinara-hw/Sayma_RTM/files/2902982/FPGA_pins.xlsx)

**Comment by sbourdeauducq** [comment]
@gkasprow Why is it XLSX now? Is that because of the Altium conversion?

**Comment by sbourdeauducq** [comment]
And what is the exact PDF schematics that corresponds to this file?

**Comment by gkasprow** [comment]
this is extracted from Altium tool. I can extract the netlist as well if U like.

**Comment by gkasprow** [comment]
I can also generate csv file

**Comment by gkasprow** [comment]
@sbourdeauducq The schematic will be in releases in a moment.

**Comment by sbourdeauducq** [comment]
@gkasprow Do you confirm that those schematics:
![image](https://user-images.githubusercontent.com/720864/53459446-cc512c80-3a74-11e9-94e3-a2ce0fb1216a.png)
correspond ***exactly*** to this file:
![image](https://user-images.githubusercontent.com/720864/53459457-d96e1b80-3a74-11e9-9276-5c5b89ad9e7a.png)

**Comment by gkasprow** [comment]
In a few hours I will publish both pdf and xls of new revision with several
issues sorted out.
Greg
