### ISSUE TITLE
DAC clock PLL

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#30]
To do:
- [x] all sign off on choice of HMC830
- [x] either add power cycler or use LDO with enable pin and add drain resistors
- [ ] add DNPd pads for 3rd order active loop filter
- [ ] route output of DAC clock fanout to FPGA via DFF. DFF clock driven by DAC clock, data input driven by FPGA to allow gating. DFF output driven to diff input in FPGA. Used for S/H validation. @sbourdeauducq to sign off on this part of the design, check frequency range, voltage standards on FPGA
- [ ] add mounting holes and IDC that can be used to for external clock board. Add UFL/MMCX to unused mux input

**Comment by hartytp** [comment]
@gkasprow are you happy with all the items on the list above?

One thing we didn't discuss on the phone was the HMC830 loop filter. Based on our experience here, passive loop filters are generally not the best for phase critical applications, so it's worth leaving ourselves the option of adding an active loop filter. Can be DNPd pads for now and we'll prototype it once we have the new hw.

**Comment by hartytp** [comment]
@sbourdeauducq asked
> Why the ADCLK948 mux and not capacitor selection?

When we were planning to scrap the HMC7043, the idea here was that we need a fanout for the PLL anyway, so why not make it a mux.

If we decide to keep the HMC7043 after all, then we don't strictly need this fanout buffer. However, I would still advocate keeping it for Sayma v2.0 on the understanding that we expect to scrap it for v2.1. The argument being that it really doesn't cost us much to include it, but could end up being useful for diagnostics
- we can use it to fanout the PLL and provide a copy of the HMC830 output on MMCX connectors for debugging
- we can really quickly swap between the HMC830 and an external PLL during tests (yes, this can be done by swapping capacitors in and out, but that becomes tedious if one wants to do the swap more than a few times)
- it means that if we do need to go to a fallback option, such as a different PLL IC, then we don't have to rework all boards by hand (and then be careful to track the rework status of each board etc)

Essentially, I still view Sayma v2.0 as a prototyping/testing platform, so I'm happy to keep a few extra pieces of hw if they are potentially useful in debugging.

**Comment by hartytp** [comment]
>     * route output of DAC clock fanout to FPGA via DFF. DFF clock driven by DAC clock, data input driven by FPGA to allow gating. DFF output driven to diff input in FPGA. Used for S/H validation. @sbourdeauducq to sign off on this part of the design, check frequency range, voltage standards on FPGA

@sbourdeauducq I assume we no longer need this, as the DAC seems to behave fine at max clock rate...

**Comment by hartytp** [comment]
> add mounting holes and IDC that can be used to for external clock board. Add UFL/MMCX to unused mux input

If we're happy with the HMC830, we can also scrap this item -- although, I still think that exposing some GPIO and supply voltages on pin header would be a very good idea

**Comment by gkasprow** [comment]
we will keep 2V5 IO pin header so we can use it for any purpose.

**Comment by gkasprow** [comment]
What loop filter would you like for HMC? Active one? So shall I add RC place holders and opamp?
Any suggestions on opamp?

**Comment by hartytp** [comment]
I'd like to have a passive loop filter (same one we currently have) fitted by default, but the pads there so we can add an active loop filter later on if testing indicates that it would help. Just use a generic SOIC8 OpAmp footprint for now.

@WeiDaZhang is thinking about active loop filters right now, and will post a recommendation for a topology to use soon.
