### ISSUE TITLE
use only one Si5324 output

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_RTM#34]
The two outputs are not synchronized (two different dividers) so they cannot be used in a det-lat scenario.

We need WR anyway so the circuit with the ADCLK mux (like on the AMC) is good.

**Comment by gkasprow** [comment]
do we really need 3 outputs? If so, I will replace LTC6957 with ADCLK944 since we don't need a mux

**Comment by gkasprow** [comment]
first read, then write :) OK, I will copy AMC side clocking..

**Comment by sbourdeauducq** [comment]
We need a mux. The RTM needs WR just like the AMC.

**Comment by gkasprow** [comment]
OK, done.
![obraz](https://user-images.githubusercontent.com/4325054/53498605-ec014880-3aa6-11e9-99f5-af2b731bf210.png)
