### ISSUE TITLE
bank 34 does not have voltage indication on schematics

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_RTM#36]
![image](https://user-images.githubusercontent.com/720864/53465404-c49b8300-3a88-11e9-8cc8-d3a539b7b0e7.png)
![image](https://user-images.githubusercontent.com/720864/53465417-c9603700-3a88-11e9-9c40-5b8d0c08c84f.png)
![image](https://user-images.githubusercontent.com/720864/53465423-cfeeae80-3a88-11e9-9153-475bee36d4d3.png)

**Comment by sbourdeauducq** [comment]
Also there is something not right with that voltage. The oscillator is 3.3V, the HW_ID resistors are 2.5V and LVDS requires 2.5V (we have only HR banks with LVDS_25). I suppose the oscillator should output 2.5V levels instead.

**Comment by sbourdeauducq** [comment]
Also, is the resistive divider that brings the 50MHz oscillator output to 2.2V something that you have done before and which yields good SI?
What about using a LVDS oscillator instead?

**Comment by gkasprow** [comment]
fixed. It is 3.3V

**Comment by sbourdeauducq** [comment]
3.3V doesn't work for LVDS.

**Comment by sbourdeauducq** [comment]
Did you mean 2.5V?

**Comment by gkasprow** [comment]
Bank 27 is connected to 3.3V to provide signaling for HMC chips and mezzanines. Other banks are connected to 2.5V and LVDS are located there.
