### ISSUE TITLE
resistive divider for 50MHz oscillator

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_RTM#37]
@gkasprow is the resistive divider that brings the 50MHz oscillator (OSC1) output to 2.2V something that you have done before and which yields good SI?
What about using a LVDS oscillator instead?

**Comment by sbourdeauducq** [comment]
Alternatively, scrap that oscillator - we can use the path through the GTP (OSC2) like we do on Kasli.

**Comment by gkasprow** [comment]
it is close to the FPGA. Impedance matching could be better. I can increase the R37 and keep effective R of roughly 50hm. CMOS oscillators are much cheaper than LVDS ones. I found it useful for testing.

**Comment by gkasprow** [comment]
this gives Z=51Ohm
![obraz](https://user-images.githubusercontent.com/4325054/53491057-aab46d00-3a95-11e9-9d2c-98d002353fc3.png)

**Comment by jordens** [comment]
I'd actually scrap OSC1. It's really easy and reliable to use the 125 MHz GT clock input for the fabric.
