### ISSUE TITLE
index DACs at 0

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_RTM#39]
Currently we have DAC1 driving MEZZ0 and DAC2 driving MEZZ1. Confusing.

**Comment by sbourdeauducq** [comment]
Well, DACs are actually indexed inconsistently:
![image](https://user-images.githubusercontent.com/720864/53468894-f0256a00-3a96-11e9-8c41-db089eb6a080.png)

**Comment by gkasprow** [comment]
done
