### ISSUE TITLE
bigger FPGA

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#4]
Context:
- there is currently a 15T on Sayma RTM which is pretty tiny
- for DRTIO we need to add Satman. Currently, that should be fine but it will require some optimisation to reduce firmware size
- adding a bigger FPGA will make it easier to get DRTIO going and reduces risks
- we can always move back to a smaller pin-compatible FPGA in a future design revision to save costs

@sbourdeauducq what size of FPGA do you think we should go for? 50T? Since this is still a prototype, let's err on the side of having too big an FPGA rather than too small.

@gkasprow what's the biggest pin-compatible FPGA we can stick on Sayma RTM?

**Comment by jordens** [comment]
The 50T is pin compatible. But as mentioned before that might not be needed at all since the bitstream is the same except for the chip name.

**Comment by hartytp** [comment]
So, the suggestion is bitstream hacking to make a 50T bitstream work on the 15T (which is the same silicon)? What's the cost difference between the two FPGAs? Is it worth the hassle of bitstream hacking?

**Comment by hartytp** [comment]
Anyway, right now my preference is to go with whatever is least effort and gets RF out of Sayma quickest. Once Sayma works and we've gauged the level of interest we can focus more on cost optimisation.

**Comment by jordens** [comment]
Place a 50T for now if the availabliity is ok and keep in mind that moving back to a 15T will require software infrastructure changes.

**Comment by sbourdeauducq** [comment]
Well, with some optimization it may even fit within the 15T limitations that Xilinx made up. But 50T on proto sounds good.

**Comment by jbqubit** [comment]
50T sounds like the lowest risk option. @gkasprow @marmeladapk Is it too late for this change to the BOM?

**Comment by gkasprow** [comment]
I will check if they are 100% compatible. Usually this involves generation of new symbol and comparison pin by pin because not always migration is that straightforward.

**Comment by marmeladapk** [comment]
According to Xilinx they are pin compatible, however we should rerun power estimator and adjust power delivery accordingly.

**Comment by gkasprow** [comment]
They usually are, but It happened to me that some IOs were swapped during migration to bigger chip or not present in smaller packages. So it is not always that simple.

**Comment by gkasprow** [comment]
Can we use XC7A35T-1CSG325 instead?

**Comment by gkasprow** [comment]
It's hard to get XC7A50T in CSG325 package

**Comment by hartytp** [comment]
I'll leave this to @sbourdeauducq and @jordens, but AFAICT a 35T should be fine.

**Comment by sbourdeauducq** [comment]
Also use a faster speed grade, -1 does not meet timing for 150MHz RTIO frequency.

**Comment by sbourdeauducq** [comment]
15, 35 and 50 are the same silicon so it doesn't matter so much which one you pick...

**Comment by jbqubit** [comment]
@sbourdeauducq   Please concur if you're happy with XC7A35T-2CSG325. 

@gkasprow Are you comfortable that the risk is low enough for this change? 

- [ ] re-run power estimator 
- [x] pin-by-pin check of new symbol

**Comment by gkasprow** [comment]
The power supply is designed with a lot o margin. I can increase the current limit even by a factor of 5.

**Comment by jordens** [comment]
XC7A35T-3CSG325 requested

**Comment by jbqubit** [comment]
@jordens Does your comment mean that @sbourdeauducq signed off on the use of 35T-3?

**Comment by jordens** [comment]
Yes. As explained and discussed in the meeting.

**Comment by gkasprow** [comment]
XC7A35T-3CSG325 used.

**Comment by kaolpr** [comment]
Long lead time for XC7A35T-3CSG325E (~14 weeks).

@sbourdeauducq @jordens @jbqubit Do you agree to use XC7A50T-3CSG325 only for the current production?

**Comment by sbourdeauducq** [comment]
OK with me. The only important thing is the speed grade 3.

**Comment by jbqubit** [comment]
XC7A50T-3CSG325 is fine by me.

**Comment by jbqubit** [comment]
@gkasprow Please indicate how you're proceeding with this and close.

**Comment by gkasprow** [comment]
We installed XC7A50T-3CSG325. It's the same silicon anyway.
