### ISSUE TITLE
consider increasing i2c pullup resistances

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Sayma_RTM#41]
Now there are at least 4 2k2 in parallel and up to ~10 worst case. I'd go for 10k pullups. I think we have the same for Banker etc.

![image](https://user-images.githubusercontent.com/1338946/53476935-dd4d6e00-3a73-11e9-93a9-96779fb5d2d8.png)

**Comment by gkasprow** [comment]
done

**Comment by gkasprow** [comment]
done for Sayma AMC as well
