### ISSUE TITLE
M2_0: add 0R

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Sayma_RTM#42]
Use a 0R instead of a direct connection.
![image](https://user-images.githubusercontent.com/1338946/53476875-b858fb00-3a73-11e9-8f39-8d2e9ca2c596.png)

**Comment by gkasprow** [comment]
done
![obraz](https://user-images.githubusercontent.com/4325054/53490461-08e05080-3a94-11e9-8a28-46a3c9f74ef0.png)
