### ISSUE TITLE
observing DAC output for debugging

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_RTM#43]
What is the plan for looking at the DAC outputs during initial board bring-up?
Should we make minimalistic AFEs with just balun transformers and connectors?

**Comment by gkasprow** [comment]
There is already one - the TestMod.

**Comment by gkasprow** [comment]
Look [here](https://github.com/sinara-hw/TestMod/wiki)

**Comment by sbourdeauducq** [comment]
Okay, good. We will need them for firmware development.

**Comment by gkasprow** [comment]
I have 4 pcs so far.

**Comment by sbourdeauducq** [comment]
We need at least 2 for DAC synchronization tests. At least 3 would be more convenient.

**Comment by hartytp** [comment]
> I have 4 pcs so far.

Is that with the proper stack up? If so, can you lend me one at some point to stick it on the VNA?

**Comment by gkasprow** [comment]
I didn't measure them yet so I cannot confirm. They are supposed to be with the right stackup.

**Comment by hartytp** [comment]
Cool. Well, if you send me one I'm happy to have a look.

**Comment by gkasprow** [comment]
OK.
