### ISSUE TITLE
spare GTP channels

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_RTM#45]
https://freenode.irclog.whitequark.org/m-labs/2019-02-27#1551260565-1551262342;

**Comment by gkasprow** [comment]
Interesting idea.
 But we decided that we will utilize all RTM connector pins to LVDS for AFE.
Is there any use case for RTM FPGA having access to the AMC side FMC?

**Comment by jordens** [comment]
I meant routing the GTPs to the RTM-AFEs (via their FMC connector), not to the AMC-FMC.

**Comment by gkasprow** [comment]
OK, this makes sense. We can do that.
Just don't use FMC name. It stands for the FPGA Mezzanine Card. I call these AFE connectors :)

**Comment by gkasprow** [comment]
which SATA shall I keep?

**Comment by gkasprow** [comment]
we can use pins e31/e32 and b31/b32

**Comment by gkasprow** [comment]
I mean master or slave SATA?

**Comment by jordens** [comment]
Master SATA (the one that connects with a crossover cable to J16 on the AMC and to Kasli) is fine. There are crossover cables IIRC easily available.

**Comment by gkasprow** [comment]
done

**Comment by jordens** [comment]
And in general we should remove those "slave SATA" things everywhere and turn them all into a single SATA pinout. The RX-TX crossover is easily done in the cable and does not restrict the connectivity options.

**Comment by elektron314** [comment]
does sata cable really have crossover inside of it?

**Comment by sbourdeauducq** [comment]
You can find some special cables that do; they are rare but they exist.

**Comment by elektron314** [comment]
so if I plan to connect two devices with SATA I need to make TX at 2,3 pins and RX at 5,6 pins on one side, and TX at 5,6 and RX at 2,3 on the other side?

**Comment by sbourdeauducq** [comment]
I would recommend buying a commercial crossover cable, SATA cables and connectors are messy to tinker with.

**Comment by elektron314** [comment]
yes, exactly commercial. But I want to make standard connection, not rare. So do I need to make inverted connection on pcb side because almost all cables are straight?

**Comment by sbourdeauducq** [comment]
IIRC I ordered them from https://www.techcable.com/sas-mini-sas-cables/sata-cables/

**Comment by sbourdeauducq** [comment]
Yes, almost all cables are straight.

**Comment by elektron314** [comment]
thank you, mister! you saved our company!
