### ISSUE TITLE
I2C switch reset

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Sayma_RTM#47]
![image](https://user-images.githubusercontent.com/1338946/53696211-2cbdd200-3dc5-11e9-892e-2b288a569805.png)

Please allow the I2C switch to be reset by the FPGA. Maybe use the SI5324_INT_ALM FPGA pin (I think we don't need that, c.f. https://github.com/sinara-hw/Sayma_AMC/issues/5#issue-391098956).

**Comment by gkasprow** [comment]
done
