### ISSUE TITLE
GPIO/debug port

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Sayma_RTM#51]
Can we have a GPIO header going to the FPGA where we can connect signals in case of unexpected problems? Include GC pins, and differential pairs.

**Comment by gkasprow** [comment]
We already have. I moved it to another bank to have access to SRCC and MRCC clock pins. I will also route them as diff pairs.
The CLK50 was moved to the 3V3 bank.
![obraz](https://user-images.githubusercontent.com/4325054/54126525-0c66c680-4408-11e9-8b1b-ac6ed7ae3be9.png)
