### ISSUE TITLE
sayma: heatsinks

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#56]
With the DACs running at 2.4GHz they get scorching hot, even with decent air flow. Might be worth small heat sinks in the next version (also for the RTM FPGA?).

**Comment by gkasprow** [comment]
I managed to place 17x17x2mm heat sinks. Even 3mm ones would fit but 2mm ones are COTS

**Comment by gkasprow** [comment]
drawing 
![obraz](https://user-images.githubusercontent.com/4325054/55752364-13edaf80-5a48-11e9-8131-4e98db4bf906.png)
