### ISSUE TITLE
Sayma v2: more test points 

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Sayma_RTM#57]
From #408. @gkasprow More test points on Sayma v2.0, please! Particularly on all the SPI buses.

**Comment by jbqubit** [comment]
Power test points on Sayma_AMC would be helpful. Please label test points too.

**Comment by hartytp** [comment]
@gkasprow did you implement this? Can we close?

**Comment by hartytp** [comment]
Could you have a go at this today please? I’ll do my review after it’s done

**Comment by jbqubit** [comment]
@gkasprow Please implement change or give update. We'd all like to see pending changes to RTM complete and design frozen.

**Comment by gkasprow** [comment]
Let's add missing test points to the issues and go on with the review.

**Comment by hartytp** [comment]
Most important are the HMC830 and HMC7043 SPI. I'd also ideally like to have 0R resistors between the HMC chips and the FPGA for debugging (e.g. if we need to disconnect some signal).

Most analog power lines should have test points. 

All I2C signals

**Comment by hartytp** [comment]
AFE power supplies, I2C

**Comment by gkasprow** [comment]
fixed
