### ISSUE TITLE
replace UFLs with MMCX?

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#63]

**Comment by sbourdeauducq** [comment]
https://github.com/sinara-hw/Sayma_AMC/issues/63#issuecomment-475515022

**Comment by jordens** [comment]
To me u.fl for jumpers, debugging, and characterisation seems preferable. Doesn't need through holes, uses less space, thinner cables. For permanent external connectivity probably not but in that case there are bigger problems.

**Comment by gkasprow** [comment]
UFL connectors consume space only on a single layer while MMCX use a lot of space on all the layers so I use them only in the places that will be used more often.
