### ISSUE TITLE
N12V0A/P12V0A diodes?

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#69]
@gkasprow I think the answer to this is "no" but to double check....

Do we need diodes on the P12V0/N12V0 lines to ensure that they start up correctly (i.e. to avoid the usual issues where one rail turns on too fast and reverse-biases the other one via OpAmp protection diodes etc)? Currently there are no such diodes on BaseMod, but with all channels populated there could be quite a lot of reverse current.

**Comment by gkasprow** [comment]
This issue was observed at the output of the LDOs.
I already implemented them.
![obraz](https://user-images.githubusercontent.com/4325054/55031143-388c6500-500e-11e9-8c80-cd4e6b300317.png)

**Comment by gkasprow** [comment]
I implemented them on BaseMod. Sayma RTM has increased startup time of the  -6V converter so it will start later than +6V

**Comment by hartytp** [comment]
What about the p and n 12v?

**Comment by gkasprow** [comment]
we did not observe such issue with these rails. I can increase the startup time of -12V converter.

**Comment by hartytp** [comment]
Ok. Ime these kinds of issues are quite dependent on what kind of load is present. Personally I’d stick the diodes there to be safe.

**Comment by gkasprow** [comment]
do you mean diodes at the DC/DC converter output? such diodes are already part of the buck converters.

**Comment by hartytp** [comment]
yes, sorry, you're right. This is an issue for LDOs, not bucks.
