### ISSUE TITLE
Capacitor between DXP and DXN

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_RTM#71]
MAX6642A datasheet states: "DXP: Combined Remote-Diode Current Source and ADC Input for Remote-Diode Channel. Place a 2200 pF capacitor between DXP and GND for noise filtering".

Should we implement this? There is 2nF worth of capacitors on AMC between DXP and DXN.

**Comment by gkasprow** [comment]
Added 2nF
