### ISSUE TITLE
Ground VP_0, VN_0?

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/Sayma_RTM#76]
UG480 says that "This pin should be connected to GND if not used."

@jordens , you raised https://github.com/sinara-hw/sinara/issues/495 , is that correct? On Kasli these pins are shorted to ground through ferride bead.

**Comment by jordens** [comment]
Kasli was originally
https://github.com/sinara-hw/sinara/issues/349#issuecomment-361272857
Vrefp and vrefn should be grounded without ferrite IIRC. dunno about vp vn.

**Comment by gkasprow** [comment]
shall we short vn and vp to GND on Sayma as well?
