### ISSUE TITLE
Si5324 I2C

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#8]
@gkasprow am I correct in thinking that currently the Si5324 I2C bus is driven by the AMC and not by the RTM FPGA. @sbourdeauducq correct me if I'm wrong, but in the new revision, don't we want the Si5324 I2C driven by the RTM FPGA?

**Comment by gkasprow** [comment]
Any of FPGAs can drive it. On both AMC and RTM side, the FPGA has access to the whole I2C network.
AMC I2C network has access to the RTM I2C network as well.
