### ISSUE TITLE
PI analysis

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Sayma_RTM#87]
P2V0 rail under 150% load
![obraz](https://user-images.githubusercontent.com/4325054/56386462-1a3b1300-6222-11e9-8f09-0ce0a01c9799.png)
We are well within the LDO limit. But current density in some places is too high.
![obraz](https://user-images.githubusercontent.com/4325054/56386652-ab11ee80-6222-11e9-91fa-d9d401850a1b.png)
LDOs were shorted to simulate the whole PDN.
After optimization, the current density does not exceed 55A/mm2
![obraz](https://user-images.githubusercontent.com/4325054/56388757-20cc8900-6228-11e9-97c0-6d66e0e0aea8.png)
and DC drop was lowered twice. Note that most of the DC drop is caused by the inductor DCR
![obraz](https://user-images.githubusercontent.com/4325054/56388796-3cd02a80-6228-11e9-84e0-81772302e081.png)

**Comment by gkasprow** [comment]
P4V0 PDN after optimization
via current
![obraz](https://user-images.githubusercontent.com/4325054/56391150-17deb600-622e-11e9-9749-c50ea28b23e0.png)

current density
![obraz](https://user-images.githubusercontent.com/4325054/56391167-288f2c00-622e-11e9-9561-5c6060fad2bd.png)

DC drop is mainly on DCR
![obraz](https://user-images.githubusercontent.com/4325054/56391209-48265480-622e-11e9-86f6-30ac4c122b55.png)

**Comment by gkasprow** [comment]
P6V0 rail after optimization
DC drop is dominated by inductors DCR
![obraz](https://user-images.githubusercontent.com/4325054/56392552-03042180-6232-11e9-983f-937dae90fea8.png)

The current density is slightly high, but lower than 67A/mm2. It cannot be easily lowered.
![obraz](https://user-images.githubusercontent.com/4325054/56392638-3d6dbe80-6232-11e9-871a-42c73dd0972b.png)

**Comment by gkasprow** [comment]
N12V0A PDN. Nothing to optimize
![obraz](https://user-images.githubusercontent.com/4325054/56393116-b3265a00-6233-11e9-8552-26c225ab933a.png)
![obraz](https://user-images.githubusercontent.com/4325054/56393125-bcafc200-6233-11e9-835f-622aebd03fc4.png)

**Comment by gkasprow** [comment]
P12V0A Nothing to optimize

**Comment by gkasprow** [comment]
N6V0: 28mV drop, max I density 22.8A/mm2, I optimized the dropout slightly,

**Comment by gkasprow** [comment]
P3V3 looked bad before optimization. After some tweaking it is OK:
drop is dominated by inductors DCR
![obraz](https://user-images.githubusercontent.com/4325054/56396165-e7067d00-623d-11e9-9834-dcdd0faaf719.png)

**Comment by dnadlinger** [comment]
Out of curiosity, is this HyperLynx? I'm sure I've seen this UI somewhere before…

**Comment by gkasprow** [comment]
@dnadlinger Yes, it is. Very similar results are produced by SiWave, but it does not have the 3D mode.

**Comment by gkasprow** [comment]
12V rail before optimization
![obraz](https://user-images.githubusercontent.com/4325054/56836541-e1311d00-6877-11e9-9ca1-1fa3e114f6ec.png)
![obraz](https://user-images.githubusercontent.com/4325054/56836578-032a9f80-6878-11e9-965d-cbb8643256ae.png)

and after some tweaking
![obraz](https://user-images.githubusercontent.com/4325054/56838527-9e267800-687e-11e9-8a4f-8dd5b1bfe7bd.png)

**Comment by gkasprow** [comment]
P1V0. Reduction of the drop from 220mV to 57mV
![obraz](https://user-images.githubusercontent.com/4325054/56838594-d2019d80-687e-11e9-878a-a99e8f95bb95.png)

**Comment by gkasprow** [comment]
P1V2
![obraz](https://user-images.githubusercontent.com/4325054/56838787-b8ad2100-687f-11e9-9a2c-112d838ccc5b.png)

**Comment by gkasprow** [comment]
P2V5
![obraz](https://user-images.githubusercontent.com/4325054/56838992-c1522700-6880-11e9-8b12-15b3ea739680.png)
