### ISSUE TITLE
DAC_JESD204B, AD9154BCPZ - Power supply 

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Sayma_RTM#88]
Power supply could be improved by: 

- [x] placing more vias and moving vias before capacitors, or placing solid, same as on oposite side.

![2019-04-24_16h05_51](https://user-images.githubusercontent.com/24258965/56666024-729f6400-66ab-11e9-9c58-247350da3e48.png)

- [x] placing track PVDD12A through capacitor C37A
![2019-04-24_16h14_43](https://user-images.githubusercontent.com/24258965/56666381-138e1f00-66ac-11e9-8325-1737042c9a83.png)

- [ ] placing via before cap C58A, C55A, C54A
![2019-04-24_16h17_53](https://user-images.githubusercontent.com/24258965/56666596-84cdd200-66ac-11e9-9256-c4aa5a8a3977.png)

**Comment by gkasprow** [comment]
Good catch!

**Comment by gkasprow** [comment]
in case of C58A etc not much can be done. But distances are so short that it does not really matter.
