### ISSUE TITLE
Internal planes

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Sayma_RTM#89]
- [ ] GND and power vias should be directly conected to planes.  Thermal reliefs causes dead copper.
![2019-04-24_16h44_01](https://user-images.githubusercontent.com/24258965/56668645-2b67a200-66b0-11e9-8204-d8bd994fd7ec.png)

**Comment by gkasprow** [comment]
which AD version do you use? Earlier versions can import rules differently.

**Comment by marmeladapk** [comment]
Altium 17 has a single rule, which can define different style of connections to through-pad, smd and vias. AD16 and earlier default to this behaviour seen above.

**Comment by filipswit** [comment]
16.1, so that coud be caused by older AD.
What about internal plane 1, in AD16.1 is unconnected.

**Comment by dhslichter** [comment]
Not to mention that thermal relief is horrible from an SI perspective...and is not needed for boards which will be oven-soldered.

**Comment by gkasprow** [comment]
Under AD19 it looks fine.
![obraz](https://user-images.githubusercontent.com/4325054/56821943-ebd7bc00-684f-11e9-98f9-14b9509227e7.png)

**Comment by filipswit** [comment]
Thermal reliefs were coused by AD16.1, Now I use A19 and it's fine.
But, Plane P2 isn't connected.
![image](https://user-images.githubusercontent.com/24258965/56901043-85dd7580-6a97-11e9-9821-e716026b32ba.png)

I don't know what is the purpose of dividing GND plane into two GNDs. It's on 3 negative layers.
![image](https://user-images.githubusercontent.com/24258965/56898619-c5a15e80-6a91-11e9-8016-31ba70aac761.png)

**Comment by gkasprow** [comment]
fixed. It was reminiscent from Xpedition version
