### ISSUE TITLE
FPGA DAC SYSREF should be generated by the RTM FPGA not the AMC FPGA

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Sayma_RTM#9]

**Comment by jbqubit** [comment]
@sbourdeauducq Do you agree?

**Comment by gkasprow** [comment]
ping @sbourdeauducq

**Comment by sbourdeauducq** [comment]
Isn't that for the FF+delay line synchronization option? Irrelevant since we use the HMC7043.
