### ISSUE TITLE
HMC830_CLK_DIST

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Sayma_RTM#90]
A 100nF decap could be placed close to IC16 power input.

**Comment by filipswit** [comment]
Via to GND could be fitted. C341 close to IC40
![image](https://user-images.githubusercontent.com/24258965/56676424-8a341800-66be-11e9-9a97-c723dc3b0fdf.png)

**Comment by gkasprow** [comment]
fixed
![obraz](https://user-images.githubusercontent.com/4325054/56839161-9fa56f80-6881-11e9-943b-2d7adfbd3fed.png)

![obraz](https://user-images.githubusercontent.com/4325054/56839170-a7fdaa80-6881-11e9-9f4c-7de154c26974.png)
