### ISSUE TITLE
Differential pairs

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Sayma_RTM#93]
Based on Saturn:

Class | Plane | Impedance
-- | -- | --
MGT | External | 95
  | Internal | 86
LVDS | External | 96
  | Internal | 93

- [x] Generally there are missing vias connecting reference planes.

- [x] Helper_DCXO could be improved by omission Mid-2 layer (blue one)
![2019-04-26_13h31_46](https://user-images.githubusercontent.com/24258965/56804928-a99a8480-6827-11e9-97fd-3f78d0958da3.png)

- [x] AMC_GT.GT0TX kind of right angle
![2019-04-26_13h43_04](https://user-images.githubusercontent.com/24258965/56805401-3d208500-6829-11e9-9ce6-ee8dcc0ef082.png)

- [x] GT16TX can be straighten
![2019-04-26_14h46_03](https://user-images.githubusercontent.com/24258965/56808536-0733ce80-6832-11e9-9162-652fea101b03.png)

- [x] MEZZ0_LVDS5 aren't well coupled
![2019-04-26_14h48_05](https://user-images.githubusercontent.com/24258965/56808668-4eba5a80-6832-11e9-8038-345137c5e591.png)

- [x] MEZZ0_LVDS6 right angle
![2019-04-26_14h48_48](https://user-images.githubusercontent.com/24258965/56808716-685ba200-6832-11e9-8285-727c8aedad51.png)

**Comment by filipswit** [comment]
Looks like these signals on botom layer don't have solid reference plane under them.
![2019-04-26_18h27_24](https://user-images.githubusercontent.com/24258965/56822410-3f96d500-6851-11e9-8e69-348fa52a38da.png)
![2019-04-26_18h27_35](https://user-images.githubusercontent.com/24258965/56822413-41609880-6851-11e9-9859-f0ed6cee37a2.png)

**Comment by gkasprow** [comment]
we don't really care about power plane below user IO lines.
