### ISSUE TITLE
Vias with opened mask

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Sayma_RTM#95]
![image](https://user-images.githubusercontent.com/24258965/56902349-64ca5400-6a9a-11e9-8c7e-93855d580841.png)
![image](https://user-images.githubusercontent.com/24258965/56902374-7875ba80-6a9a-11e9-98e1-fd0727ac3acf.png)
![image](https://user-images.githubusercontent.com/24258965/56902456-a4913b80-6a9a-11e9-8aea-6c4f706d7302.png)
![image](https://user-images.githubusercontent.com/24258965/56902546-cf7b8f80-6a9a-11e9-9474-203114fd0d6f.png)

**Comment by gkasprow** [comment]
fixed
