### ISSUE TITLE
Annular rings on negative innerlayers

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Sayma_RTM#96]
I think these annualar rings on negative innerlayer are improper.
![2019-04-29_13h58_06](https://user-images.githubusercontent.com/24258965/56960197-53dc1a00-6b50-11e9-8025-3658a54925a7.png)
![2019-04-29_14h02_55](https://user-images.githubusercontent.com/24258965/56960199-550d4700-6b50-11e9-8bc4-b3d91d4ff14c.png)
![2019-04-29_14h03_54](https://user-images.githubusercontent.com/24258965/56960201-56d70a80-6b50-11e9-8a86-8a532a0a566a.png)

**Comment by gkasprow** [comment]
there is no such rule to set up in AD19. Minimum annular ring rule works only on positive layers. I went through vias and corrected them manually.
