### ISSUE TITLE
layout improvement: vias

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Sayma_RTM#97]
By moving vias, planes will be connected directly instead of by wires.
![image](https://user-images.githubusercontent.com/24258965/56962439-da93f580-6b56-11e9-89af-f1bc4a1a6a65.png)

**Comment by gkasprow** [comment]
@filipswit many issues were fixed in the latest release. Do you look at the recent file?

**Comment by filipswit** [comment]
@gkasprow I have yesterday's version.
