### ISSUE TITLE
Layout improvement: components placement

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Sayma_RTM#98]
Just thinking if this kind of layout wouldn't be better for signal (as an example output from buffer IC58): 
![image](https://user-images.githubusercontent.com/24258965/56903774-3bf78e00-6a9d-11e9-8ebc-3dd1dff1ad45.png)

instead of this:
![image](https://user-images.githubusercontent.com/24258965/56903785-4154d880-6a9d-11e9-91b0-527609d9a3f2.png)

**Comment by gkasprow** [comment]
I placed single ended 50R lines to solve the issue.
